import express from 'express';
import cors from 'cors';

const app = express();
const PORT = 8080;

app.use(cors()); // Allow requests from the React frontend

// Mock fingerprint template. In a real scenario, this is a base64 hash generated by the ZK9500 scanner.
const MOCK_TEMPLATE = "ZKTeco_Mock_Template_ABC123_XYZ890";

app.get('/api/capture', (req, res) => {
    console.log('Received request from web app to capture fingerprint...');
    
    // Simulate the delay of placing a finger on the scanner
    setTimeout(() => {
        console.log('Fingerprint "captured" successfully. Sending to browser...');
        res.json({
            success: true,
            template: MOCK_TEMPLATE
        });
    }, 2000); // 2 second delay to simulate scanning
});

app.listen(PORT, '127.0.0.1', () => {
    console.log(`=================================================`);
    console.log(` MOCK ZKTECO BRIDGE RUNNING ON PORT ${PORT}`);
    console.log(`=================================================`);
    console.log(`This is a simulation bridge. It will respond to your`);
    console.log(`web app with a fake fingerprint template so you can`);
    console.log(`test your UI logic without the real hardware yet.`);
    console.log(`Waiting for requests from the browser...`);
});
